library(data.table)
library(dplyr)
setwd ('E:/FER_posao/Coursera_Iversity/Data Scientist Specialization/4 Exploratory data analysis/Peer assesment 1')
unzip("exdata-data-household_power_consumption.zip")
currwd <- getwd()
dt <- tbl_df(read.table("household_power_consumption.txt", header=TRUE, sep=";",na.strings = c("?","")))
dt$Date <- as.Date(dt$Date,"%d/%m/%Y")
dt$timetemp <- paste(dt$Date, dt$Time)
dt$Time <- strptime(dt$timetemp, format ="%Y-%m-%d %H:%M:%S")
dt_use <- subset(dt,Date >= "2007-02-01" & Date <= "2007-02-02")
png('E:/FER_posao/Coursera_Iversity/Data Scientist Specialization/4 Exploratory data analysis/Peer assesment 1/plot2.png')
plot(dt_use$Time,dt_use$Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)")
dev.off()
